const data = [
     {
          folio: 1001,
          placas: 'A-1566',
          cruces: 'Cruce 1 y cruce 2',
          articuloId: 1,
          municipios: 'municipio test',
     },
     {
          folio: 1002,
          placas: 'B-9864',
          cruces: 'Cruce 3 y cruce 4',
          articuloId: 2,
          municipios: 'municipio test',
     },
     {
          folio: 1003,
          placas: 'c-G785',
          cruces: 'Cruce 5 y cruce 6',
          articuloId: 3,
          municipios: 'municipio test',
     },
     {
          folio: 1004,
          placas: 'jal-1245',
          cruces: 'Cruce 7 y cruce 8',
          articuloId: 5,
          municipios: 'municipio test',
     },
     {
          folio: 1005,
          placas: 'jal-7854',
          cruces: 'Cruce 9 y cruce 10',
          articuloId: 10,
          municipios: 'municipio test',
     },
     {
          folio: 1006,
          placas: 'AGS-7785',
          cruces: 'Cruce 11 y cruce 12',
          articuloId: 4,
          municipios: 'municipio test',
     },
     {
          folio: 1007,
          placas: 'AGS-156699',
          cruces: 'Cruce 13 y cruce 14',
          articuloId: 2,
          municipios: 'municipio test',
     },
     {
          folio: 1008,
          placas: 'BAG-9864',
          cruces: 'Cruce 15 y cruce 16',
          articuloId: 5,
          municipios: 'municipio test',
     },
     {
          folio: 1009,
          placas: 'COL-G785',
          cruces: 'Cruce 17 y cruce 18',
          articuloId: 9,
          municipios: 'municipio test',
     },
     {
          folio: 1010,
          placas: 'jal-9945',
          cruces: 'Cruce 117 y cruce 118',
          articuloId: 1,
          municipios: 'municipio test',
     },
     {
          folio: 1011,
          placas: 'jalq-123',
          cruces: 'Cruce 119 y cruce 1110',
          articuloId: 11,
          municipios: 'municipio test',
     },
     {
          folio: 1012,
          placas: 'AGS-1047',
          cruces: 'Cruce 111 y cruce 121',
          articuloId: 2,
          municipios: 'municipio test',
     },
     {
          folio: 1013,
          placas: 'ALD-1566',
          cruces: 'Cruce 192 y cruce 201',
          articuloId: 1,
          municipios: 'municipio test',
     },
     {
          folio: 1014,
          placas: 'BAC-9864',
          cruces: 'Cruce 443 y cruce 124',
          articuloId: 5,
          municipios: 'municipio test',
     },
     {
          folio: 1016,
          placas: 'LA-G785',
          cruces: 'Cruce 502 y cruce 601',
          articuloId: 3,
          municipios: 'municipio test',
     },
     {
          folio: 1017,
          placas: 'jal-9999',
          cruces: 'Cruce 125 y cruce 825',
          articuloId: 9,
          municipios: 'municipio test',
     },
     {
          folio: 1018,
          placas: 'jal-1045',
          cruces: 'Cruce 904 y cruce 104',
          articuloId: 8,
          municipios: 'municipio test',
     },
     {
          folio: 1019,
          placas: 'AGS-1045',
          cruces: 'Cruce 145 y cruce 120',
          articuloId: 4,
          municipios: 'municipio test',
     },
];

export default data;